### ISSUE TITLE
Transaction are not going through via BlockWallet

### ISSUE THREAD

**Issue by locknprofit** [block-wallet/extension#254] opened 2022-12-05 14:43 UTC
**Describe the bug**
My transaction is failing using the XEN Batch Minter on Cointools.app . I've done 3 and they all fail using Blockwallet, and I also did one through Metamask with success, see below.

** Failed Transactions ** 
- https://etherscan.io/tx/0x07c0f6b9c80fbbd728bf0ab4f195a2a9adcd4e9d75dc4a7c4507068e9b01a2b2
- https://etherscan.io/tx/0x03c60ae62b5b34983233b5e12513cea519d1b83245a68d91ec95cff62e866a3a
- https://etherscan.io/tx/0xcd6769c3b69ba7795486fb56f13405219d149ae2e83583645fd2c8fa66895443

** This transaction worked via Metamask **
- https://etherscan.io/tx/0xe6fa7509e1672e13900287b9e542d86dd52d1f0e3bd9608ca5e36e14c884040b

**Screenshots**
As requested by Julian simulate a transaction (without confirming it) and share a screenshot where we can see gas configurations.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave
 - Version v1.46.134 (Dec 3, 2022)

![Screenshot 2022-12-05 093954](https://user-images.githubusercontent.com/119871726/205664814-b87c440d-0336-49a9-885a-bc75113c21bd.png)
![Screenshot 2022-12-05 094020](https://user-images.githubusercontent.com/119871726/205664820-d03f94b9-7009-4c70-ae47-44cc4f503bef.png)

**Comment by julianariel** [comment] 2022-12-16 18:58
hey @locknprofit , thanks for the detailed submission!

We've been working on some improvements to the estimation process, and now we allow dApps to estimate gas more accurately.

The issue is fixed in the latest BlockWallet version, so sending a similar transaction should work straight now.

Let us know if you have any other problem,

Thanks

**Closed by julianariel** 2022-12-16 18:58 UTC
Labels: in progress
